hljs:
  highlightAuto: true
  languages:
    - css
    - js
toc:

  - name: Prop Styles
    children:
      - space
      - sizes
      - colors
      - flex
      - flexItem
      - display
      - position
      - float
      - overflow
      - border
      - text
      - fontFamily
      - textStyle
      - typography
      - utility
      - ratio
      - base
      - system

  - name: Creating Prop Styles and Theme
    children:
      - createPropStyles
      - createSizeProp
      - createSpaceProps
      - createSpaceStyle
      - createColorProp
      - createPaletteProp
      - createStyleFromTheme
      - propStylesInTheme

  - name: Misc
    children:
      - cssProp
      - propSelector
      - mediaPropSelector
      - combineSelectors
      - themeSelector

  - name: Types
    children:
      - PropStylesObj
      - PropStyleFn
