hljs:
  highlightAuto: true
  languages:
    - css
    - js
toc:
  - name: Creating Prop Styles and Theme
    children:
      - createPropStyles
      - createTheme
      - name: Types
        children:
          - PropStylesObj
          - PropStyleFn
  - name: Space
    file: ./docs/space.md
    children:
      - space
      - name: Utils
        children:
          - createSpaceProps
          - createSpaceStyle

  - name: Sizes
    file: ./docs/sizes.md
    children:
      - sizes
      - name: Utils
        children:
          - sizeProp

  - name: Colors
    file: ./docs/colors.md
    children:
      - colors
      - name: Utils
        children:
          - colorProp
          - themeProp

  - name: Styles in Theme
    children:
      - propStylesInTheme

  - name: Other Prop Styles
    children:
      - flex
      - flexItem
      - display
      - position
      - float
      - overflow
      - border
      - text
      - utility
      - ratio
      - base
      - system

  - name: Misc
    children:
      - cssProp
      - propSelector
      - mediaPropSelector
      - combineSelectors
