hljs:
  highlightAuto: true
  languages:
    - css
    - js
toc:
  - name: Creating Theme and Prop Styles
    description: |
      > Basic intro to design system goes here
      {@link createTheme}
      {@link createPropStyles}
    children:
      - createTheme
      - createPropStyles
      - name: Types
        children:
          - PropStylesObj
