hljs:
  highlightAuto: true
  languages:
    - css
    - js

toc:
  - name: Systems
    children:
      - space
      - sizes
      - colors
      - box
      - boxStyle
      - text
      - textStyle

  - name: Styles
    children:
      - backgroundColor
      - border
      - borderColor
      - borderRadius
      - boxContentAlignment
      - boxItemsAlignment
      - boxSelfAlignment
      - boxShadow
      - cursor
      - display
      - flex
      - flexContainer
      - fontFamily
      - fontSize
      - fontWeight
      - gap
      - grid
      - gridItem
      - hide
      - letterSpacing
      - lineHeight
      - margin
      - opacity
      - order
      - outline
      - overflow
      - padding
      - position
      - positionOffsets
      - ratio
      - textAlign
      - textColor
      - textOverflow
      - transform
      - transition
      - whiteSpace
      - zIndex
      - atomic

  - name: Mixins
    children:
      - themePath
      - mq
      - prop

  - name: Utils
    children:
      - combineStyles
      - rem
      - px
      - splitUnit

  - name: Custom Styles
    children:
      - createStyles
      - rule
      - boolValue
      - sizeValue
      - percentageValue
      - spaceValue
      - colorValue
      - themeValue
      - mediaStyle
      - createRule
      - variant
      - style
