hljs:
  highlightAuto: true
  languages:
    - css
    - js

toc:
  - name: Styles
    children:
      - space
      - sizes
      - colors
      - boxStyle
      - flex
      - flexItem
      - display
      - position
      - float
      - overflow
      - border
      - fontFamily
      - textStyle
      - textHelpers
      - ellipsis
      - outline
      - opacity
      - radius
      - cursor
      - transition
      - transform
      - cssProp
      - ratio
      - base
      - typography
      - system

  - name: Custom Styles
    children:
      - createStyles
      - rule
      - boolValue
      - sizeValue
      - spaceValue
      - colorValue
      - themeValue
      - mediaRule
      - themeStyle
      - createVariant

  - name: Selectors
    children:
      - propSelector
      - themeSelector
      - combineSelectors

  - name: Getters
    children:
      - themePath
      - mq
