hljs:
  highlightAuto: true
  languages:
    - css
    - js
toc:
  - name: Creating Prop Styles and Theme
    description: |
      > Intro for creating design system goes here
    children:
      - createPropStyles
      - createTheme
      - ruleProp
      - name: Types
        children:
          - PropStylesObj
  - name: Space
    description: |
      Utils for creating space system for setting `margin` or `padding`.

      - If value is a `number` it takes value from `theme.space` `array` by index
      - Negative value for negative margins
      - If value is a `string` it passed as raw CSS value (like `'10%'` or `'100vh'`)
      - `true` value is equal `1` index in space array
      - `false` value is equal `0` index in space array

      All examples assume that [`theme`](#createtheme) has:

      ```js
      {
        media: {
          default: null,
          M: `(max-width: 600px)`
        },
        space: {
          default: [ 0, 10, 20, 40, 80 ],
          M: [ 0, 8, 16, 32, 64 ],
        }
      }
      ```

    children:
      - createSpaceProps
      - createSpaceStyle

  - name: Sizes
    children:
      - sizeProp

  - name: Colors
    children:
      - themeProp
      - colorProp
