hljs:
  highlightAuto: true
  languages:
    - css
    - js

toc:
  - name: Prop Styles
    children:
      - space
      - sizes
      - colors
      - flex
      - flexItem
      - display
      - position
      - float
      - overflow
      - border
      - fontFamily
      - textStyle
      - textHelpers
      - ellipsis
      - utility
      - cssProp
      - ratio
      - base
      - typography
      - system

  - name: Custom Styles
    children:
      - createPropStyles
      - rule
      - boolValue
      - sizeValue
      - spaceValue
      - colorValue
      - themeValue
      - mediaRule

  - name: Selectors
    children:
      - propSelector
      - themeSelector
      - combineSelectors

  - name: Getters
    children:
      - themePath
      - mq

  - name: Types
    children:
      - PropStyles
      - PropStyle
