hljs:
  highlightAuto: true
  languages:
    - css
    - js

toc:
  - name: Prop Styles
    children:
      - space
      - sizes
      - colors
      - flex
      - flexItem
      - display
      - position
      - float
      - overflow
      - border
      - textStyle
      - fontFamily
      - ellipsis
      - text
      - typography
      - utility
      - cssProp
      - ratio
      - base
      - system

  - name: Selectors
    children:
      - propSelector
      - mediaPropSelector
      - combineSelectors
      - themeSelector

  - name: Customization
    children:
      - createPropStyles
      - createSpace
      - sizeValue
      - colorValue
      - createPaletteStyle
      - createThemeStyle
      - createSpaceMixin

  - name: Types
    children:
      - PropStyles
      - PropStyle
