hljs:
  highlightAuto: true
  languages:
    - css
    - js

toc:
  - name: Styles
    children:
      - space
      - sizes
      - colors
      - border
      - boxStyle
      - cursor
      - direction
      - display
      - ellipsis
      - flex
      - flexItem
      - float
      - fontFamily
      - opacity
      - outline
      - overflow
      - position
      - radius
      - ratio
      - text
      - textStyle
      - transform
      - transition
      - name: atomic
        children:
          - atomicDirection
          - atomicDisplay
          - atomicFlexItem
          - atomicPosition
          - atomicSizes

  - name: Combinations
    children:
      - base
      - typography
      - system
      - atomic

  - name: Custom Styles
    children:
      - createStyles
      - rule
      - boolValue
      - sizeValue
      - spaceValue
      - colorValue
      - themeValue
      - mediaRule
      - themeStyle
      - createVariant

  - name: Selectors
    children:
      - propSelector
      - themeSelector
      - combineSelectors

  - name: Getters
    children:
      - themePath
      - mq

  - name: Utils
    children:
      - combineStyles
