hljs:
  highlightAuto: true
  languages:
    - css
    - js

toc:
  - name: Systems
    children:
      - space
      - sizes
      - colors
      - boxStyle
      - textStyle
      - text

  - name: Styles
    children:
      - border
      - boxContentAlignment
      - boxItemsAlignment
      - boxSelfAlignment
      - clearFix
      - cursor
      - direction
      - display
      - ellipsis
      - flex
      - flexBox
      - float
      - fontFamily
      - fontSize
      - fontWeight
      - gap
      - grid
      - gridItem
      - hideOn
      - letterSpacing
      - lineHeight
      - opacity
      - order
      - outline
      - position
      - radius
      - ratio
      - textAlign
      - transform
      - transition
      - whiteSpace
      - zIndex

  - name: Atomic Styles
    children:
      - atomic
      - atomicDirection
      - atomicDisplay
      - atomicFlexItem
      - atomicPosition
      - atomicSizes
