hljs:
  highlightAuto: true
  languages:
    - css
    - js

toc:
  - name: Systems
    children:
      - space
      - sizes
      - colors
      - boxStyle
      - textStyle
      - fontVariant

  - name: Styles
    children:
      - border
      - boxContentAlignment
      - boxItemsAlignment
      - boxSelfAlignment
      - clearFix
      - cursor
      - direction
      - display
      - ellipsis
      - flex
      - flexBox
      - float
      - gap
      - grid
      - gridItem
      - hideOn
      - opacity
      - order
      - outline
      - position
      - radius
      - ratio
      - text
      - transform
      - transition
      - zIndex

  - name: Atomic Styles
    children:
      - atomic
      - atomicDirection
      - atomicDisplay
      - atomicFlexItem
      - atomicPosition
      - atomicSizes

  - name: Custom Styles
    children:
      - createStyles
      - rule
      - boolValue
      - sizeValue
      - percentageValue
      - spaceValue
      - colorValue
      - themeValue
      - mediaStyle
      - themeStyle
      - createRule
      - createVariant

  - name: Selectors
    children:
      - propSelector
      - themeSelector
      - combineSelectors

  - name: Mixins
    children:
      - themePath
      - mq
      - prop

  - name: Utils
    children:
      - combineStyles
      - rem
      - px
      - splitUnit
