hljs:
  highlightAuto: true
  languages:
    - css
    - js
toc:
  - name: Creating Prop Styles and Theme
    description: |
      > Intro for creating design system goes here
    children:
      - createPropStyles
      - createTheme
      - name: Types
        children:
          - PropStylesObj
