hljs:
  highlightAuto: true
  languages:
    - css
    - js
toc:
  - propStylesSystem
  - createTheme
  # - spaceProps
  # - ruleProp
  # - sizeProp
  # - colorProp
  # - themeProp
  - name: Types
  - PropStyles
